### ISSUE TITLE
Fix: add some space in your search icon 

### ISSUE THREAD

**Issue by AbbeyIT** [eloybernardez/Google-clone#4]
I suggest that you can add some space between the search icon and the typing line
![image](https://user-images.githubusercontent.com/93916892/185033133-a2d68267-8799-44d8-80a6-8ac1981ec738.png)

**Comment by eloybernardez** [comment]
Hi Abbey!

Thank you so much for your contribution :)

![google](https://user-images.githubusercontent.com/91396405/185127688-07c97378-2f0d-4dc6-ad8d-93c0eef50281.png)

I've already fixed it.

I hope you are having a great day :D
